version: '3.7'
services:
    web:
        build:
            context: ""
            dockerfile: Dockerfile
        ports:
            - "9100:9100"
        environment:
            - REDIS_HOST=redis
        restart: always
        command: "npm run start:dev"
        networks:
            - redis-network

    redis:
        image: redis:alpine
        networks:
            - redis-network

networks:
    redis-network:
        driver: bridge
