version: '3.7'
services:
    web:
        image: domready/tocgs:0.2.0-alpha
        build:
            context: ""
            dockerfile: Dockerfile
        ports:
            - "9100:9100"
        environment:
            - REDIS_HOST=redis
        env_file:
            - game.env
        restart: always
        command: "npm run start:prod"
        depends_on:
          - redis

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
