version: '3.7'
services:
    web:
        image: domready/tocgs:0.1.1
        build:
            context: ""
            dockerfile: Dockerfile
        ports:
            - "9100:9100"
        environment:
            - REDIS_HOST=redis
        restart: always
        command: "npm run start:dev"
        volumes:
            - ./dist:/usr/src/game-server/dist
        depends_on:
          - redis

    redis:
        image: redis:alpine

