export interface AllResourceInterface<T = any> {
    treeTrunks: T;
    stones: T;
    timber: T;
    ironOre: T;
    goldOre: T;
    coal: T;
    iron: T;
    gold: T;
    vine: T;
    corn: T;
    loaves: T;
    flour: T;
    leather: T;
    sausages: T;
    pigs: T;
    skins: T;
    woodenShield: T;
    longShield: T;
    leatherArmor: T;
    ironAmament: T;
    handAxe: T;
    sword: T;
    lance: T;
    pike: T;
    longbow: T;
    crossbow: T;
    horses: T;
    [key: string]: T;
}

export interface ResourceInterface<T = any> {
    treeTrunks?: T;
    stones?: T;
    timber?: T;
    ironOre?: T;
    goldOre?: T;
    coal?: T;
    iron?: T;
    gold?: T;
    vine?: T;
    corn?: T;
    loaves?: T;
    flour?: T;
    leather?: T;
    sausages?: T;
    pigs?: T;
    skins?: T;
    woodenShield?: T;
    longShield?: T;
    leatherArmor?: T;
    ironAmament?: T;
    handAxe?: T;
    sword?: T;
    lance?: T;
    pike?: T;
    longbow?: T;
    crossbow?: T;
    horses?: T;
    [key: string]: T;
}
