#!/bin/bash

echo Build nightly!;
cd /home/dominik/Development/toc-online/game-frontend;
git pull origin master
rm -rf ./dist/*
docker run --rm -ti \
 --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') \
 --env ELECTRON_CACHE="/home/dominik/docker-images/.cache/electron" \
 --env ELECTRON_BUILDER_CACHE="/home/dominik/docker-images/.cache/electron-builder" \
 -v ${PWD}:/project \
 -v ${PWD##*/}-node-modules:/project/node_modules \
 -v /home/dominik/docker-images/.cache/electron:/root/.cache/electron \
 -v /home/dominik/docker-images/.cache/electron-builder:/root/.cache/electron-builder \
 electronuserland/builder:wine \
 /bin/bash -c "npm install && npm run build:js && npm run build";
scp ./dist/* /www/htdocs/w017d2fb/download/nightly;